version: '2'
services:
    bestand:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - "TZ=Europe/Berlin"
        ports:
            - "5000:5000"