swagger: '2.0'

info:
  version: "1.0.0"
  title: Bestand Service
  description: API um auf die Daten des Hamburger Stadtrads zuzugreifen

paths:
  /bestand:
    get:
      description: Listet alle bekannten Stationen auf
      responses:
        '200':
          description: Anfrage erfolgreich
          schema:
            title: Array aller Stationen
            type: array
            items: {
              "$ref": "#/definitions/Bestand an Station"
            }
  /bestand/{stationsName}:
    get:
      description: Gibt den Bestand f端r eine bestimmte Station zur端ck
      parameters:
        - name: stationsName
          in: path
          description: Name der angefragten Station
          type: string
          required: true
      responses:
        '200':
          description: Anfrage erfolgreich
          schema: {
              "$ref": "#/definitions/Bestand an Station"
            }
  /bestandUndVorhersage:
    post:
      description: Gibt Bestand und Vorhersage fuer die angegebenen Stationen an
      parameters:
        - name: stations
          in: body
          description: Namen der angefragten Stationen
          schema:
            type: array
            items: {
              "$ref": "#/definitions/Station"
            }
      responses:
        200:
          description: Anfrage erfolgreich
          schema:
            title: Array Stationen mit Vorhersagen
            type: array
            items: {
              "$ref": "#/definitions/Vorhersage und Bestand f端r Station"
            }


definitions:
  Station:
    type: object
    properties:
      name:
        type: string
  Bestand an Station:
    type: object
    properties:
      name:
        type: string
      bikes:
        type: integer
  Vorhersage und Bestand f端r Station:
    type: object
    properties:
      name:
        type: string
      bikes:
        type: integer
      prediction:
        type: integer
      history:
        type: array