swagger: '2.0'

info:
  version: "0.0.0"
  title: Bestand Service

paths:
  /bestand:
    get:
      description: Listet alle bekannten Stationen auf
      responses:
        '200':
          description: Successful response
          schema:
            title: Array aller Stationen
            type: array
            items: {
              "$ref": "#/definitions/Station"
            }
  /bestand/{stationName}:
    get:
      description: Listet alle bekannten Stationen auf
      parameters:
        - name: stationName
          in: path
          description: 'get bike count for specific station'
          type: string
          required: true
      responses:
        '200':
          description: Successful response
          schema: {
              "$ref": "#/definitions/Station"
            }


definitions:
  Station:
    type: object
    properties:
      name:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      bikes:
        type: integer