swagger: '2.0'

info:
  version: "1.0.0"
  title: Bestand Service
  description: API um auf die Daten des Hamburger Stadtrads zuzugreifen

paths:
  /bestand:
    get:
      description: Listet alle bekannten Stationen auf
      responses:
        '200':
          description: Anfrage erfolgreich
          schema:
            title: Array aller Stationen
            type: array
            items: {
              "$ref": "#/definitions/Station"
            }
  /bestand/{stationName}:
    get:
      description: Gibt den Bestand für eine bestimmte Station zurück
      parameters:
        - name: stationName
          in: path
          description: Name der angefragten Station
          type: string
          required: true
      responses:
        '200':
          description: Anfrage erfolgreich
          schema: {
              "$ref": "#/definitions/Station"
            }
  /bestandUndVorhersage:
    get:
      description: Gibt Bestand und Prediction fuer die angegebenen Stationen an
      parameters:
        - name: count
          in: query
          description: Anzahl der angefragten Stationen
          type: integer
          required: true
        - name: stations
          in: body
          description: Namen der angefragten Stationen
          schema:
            type: array
            items:
              required:
                - stationName
              properties:
                stationName:
                  type: string
                latidude:
                  type: number
                longitude:
                  type: number
      responses:
        200:
          description: Anfrage erfolgreich
          schema: {
            "$ref": "#/definitions/Station"
          }
        

definitions:
  Station:
    type: object
    properties:
      name:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      bikes:
        type: integer